name: Library - Deploy only
on:
  workflow_call:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false
      environment:
        description: "Environment to deploy to"
        type: string
        required: true

jobs:
  ref:
    name: Load Commit Ref
    runs-on: ubuntu-latest
    steps:
      - id: ref
        uses: passportxyz/gh-workflows/.github/actions/load_commit_ref@main
        with:
          commit: ${{ inputs.commit }}

    outputs:
      version_tag: ${{ steps.ref.outputs.version_tag }}
      docker_tag: ${{ steps.ref.outputs.docker_tag }}
      refspec: ${{ steps.ref.outputs.refspec }}

  deploy_preview:
    name: Preview - Deploying AWS Infra
    needs: [ref]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/PULUMI_ACCESS_TOKEN
      - name: Prepare to Deploy to AWS
        uses: passportxyz/gh-workflows/.github/actions/prepare_deploy_to_aws@main
      - name: Deploy Review
        uses: passportxyz/gh-workflows/.github/actions/deploy_to_aws@main
        with:
          docker_tag: ${{ needs.ref.outputs.docker_tag }}
          stack_name: passportxyz/scroll-badge-service/${{ inputs.environment }}
          aws_region: us-west-2
          pulumi_command: preview
          pulumi_diff: true
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

  deploy_confirm:
    name: Review Approval Pending
    needs: [ref, deploy_preview]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Approve Release to Review (check pulumi preview)
        run: |
          echo "Ref" ${{ needs.ref.outputs.refspec }}

  deploy_backends:
    name: Deploying AWS Infra
    needs: [ref, deploy_preview, deploy_confirm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/ci/PULUMI_ACCESS_TOKEN
      - name: Prepare to Deploy to AWS
        uses: passportxyz/gh-workflows/.github/actions/prepare_deploy_to_aws@main
      - name: Deploy Review
        uses: passportxyz/gh-workflows/.github/actions/deploy_to_aws@main
        with:
          docker_tag: ${{ needs.ref.outputs.docker_tag }}
          stack_name: passportxyz/scroll-badge-service/${{ inputs.environment }}
          pulumi_command: up
          aws_region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
